#
# Ref:
#   - https://api.slack.com/docs/message-formatting
#   - https://api.slack.com/docs/message-attachments
#   - https://api.slack.com/interactive-messages
#   - https://api.slack.com/docs/message-buttons
#   - https://api.slack.com/docs/interactive-message-field-guide
#

description: |
  Send deployment notifications to Slack.

parameters:
  webhook:
    description: the Slack webhook url for posting the notification
    type: string
  color:
    description: the color of notification message on Slack
    type: string
  environment:
    description: the environment in which the artifact was deployed
    type: string
  region:
    description: the region in which the artifact was deployed
    type: string
  artifact:
    description: the name of artifact which was deployed
    type: string
  version:
    description: the version of artifact which was deployed
    type: string
  include_actions:
    description: whether or not to include action buttons in the notification
    type: boolean
    default: false

steps:
  - run:
      name: Send Deployment Notification To Slack
      command: |
        git_tag=$(git tag --list --points-at HEAD)
        commit_sha=$(git rev-parse --verify HEAD)
        commit_message=$(git log --oneline -n1 | cut -c9-)
        github_user_name=$(curl -s "https://api.github.com/users/$CIRCLE_USERNAME" | jq -r '.name')
        github_avatar_url=$(curl -s "https://api.github.com/users/$CIRCLE_USERNAME" | jq -r '.avatar_url')

        # Feature branch / Pull request
        if [[ -n "$CIRCLE_PULL_REQUEST" ]]; then
          pr_number=$(echo $CIRCLE_PULL_REQUEST | rev | cut -d '/' -f1 | rev)
          title="Pull Request: $commit_message"
          title_link="$CIRCLE_PULL_REQUEST"
        # Release Tag
        elif [[ "$CIRCLE_BRANCH" == "master" && "$git_tag" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          title="Release Changelog: $git_tag"
          title_link="https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/releases/tag/$git_tag"
        # Default
        else
          title="Commit Diff: $commit_message"
          title_link="https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/commit/$CIRCLE_SHA1"
        fi

        curl \
          -H 'Content-type: application/json' \
          -X POST "<<parameters.webhook>>" \
          --data \
            "{
              \"attachments\": [{
                \"fallback\": \"Deployed <<parameters.artifact>> with version <<parameters.version>> in <<parameters.environment>>/<<parameters.region>>\",
                \"color\": \"<<parameters.color>>\",
                \"author_name\": \"$github_user_name\",
                \"author_link\": \"https://github.com/$CIRCLE_USERNAME\",
                \"author_icon\": \"$github_avatar_url\",
                \"title\": \"$title\",
                \"title_link\": \"$title_link\",
                \"text\": \"Deployed \`<<parameters.artifact>>\` version \`<<parameters.version>>\` in \`<<parameters.environment>>/<<parameters.region>>\`\",
                \"actions\": [
                  <<# parameters.include_actions >>
                  {
                    \"type\": \"button\",
                    \"name\": \"followup\",
                    \"value\": \"verified\",
                    \"text\": \"Verify\",
                    \"style\": \"primary\"
                  },
                  {
                    \"type\": \"button\",
                    \"name\": \"followup\",
                    \"value\": \"rollback\",
                    \"text\": \"Rollback\",
                    \"style\": \"danger\"
                  }
                  <</ parameters.include_actions >>
                ]
              }]
            }"
