#
# REF:
#   https://circleci.com/orbs/registry/orb/circleci/circleci-cli
#   https://circleci.com/orbs/registry/orb/circleci/orb-tools
#   https://circleci.com/orbs/registry/orb/circleci/build-tools
#   https://circleci.com/orbs/registry/orb/iynere/compare-url
#   https://github.com/CircleCI-Public/orb-tools-orb
#   https://github.com/CircleCI-Public/circleci-orbs
#

version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.3
  compare-url: iynere/compare-url@0.4.9

jobs:

  lint:
    docker:
      - image: moorara/tools
    steps:
      - checkout
      - run:
          name: Ensure .yamllint
          command: |
            touch .yamllint || true
            cat > .yamllint \<< EOF
            extends: relaxed
            rules: 
              line-length: 
                max: 200 
                allow-non-breakable-inline-mappings: true
            EOF
      - run:
          name: Linting Orbs
          command: yamllint src

  pack:
    executor: cli/default
    steps:
      - checkout
      - compare-url/reconstruct:
          circle-token: CIRCLECI_API_TOKEN
      - run:
          name: Pack Modified Orbs
          command: |
            CIRCLE_COMPARE_URL=$(cat CIRCLE_COMPARE_URL.txt)
            COMMIT_RANGE=$(echo $CIRCLE_COMPARE_URL | sed 's:^.*/compare/::g')

            # Create the top-level directory, so persist_to_workspace does not fail
            mkdir -pv orbs

            for orbpath in src/*/; do
              orbname=$(basename $orbpath)
              if [[ $(git diff $COMMIT_RANGE --name-status | grep "$orbname") ]]; then
                # Create a sub-directory for the orb
                mkdir -pv "orbs/${orbname}"

                echo -e "\n\033[1;36m Packing orb ${orbname} ... \033[0m"
                circleci config pack "${orbpath}" > "orbs/${orbname}/orb.yml"

                echo -e "\n\033[1;36m Validating orb ${orbname} ... \033[0m"
                circleci orb validate "orbs/${orbname}/orb.yml"
              else
                echo -e "\033[1;33m SKIPPED: orb ${orbname} not modified. \033[0m"
              fi
            done
      - store_artifacts:
          path: orbs/
      - persist_to_workspace:
          root: .
          paths:
            - orbs

  publish-dev:
    executor: cli/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Publish Modified Orbs
          command: |
            namespace="moorara"
            version="dev:${CIRCLE_SHA1:0:7}"

            for orbpath in orbs/*/; do
              if [[ -d $orbpath ]]; then
                orbname=$(basename $orbpath)

                echo -e "\n\033[1;36m Publishing orb ${orbname} ... \033[0m"
                circleci orb publish "${orbpath}/orb.yml" "${namespace}/${orbname}@${version}" --token "$CIRCLECI_API_TOKEN"
              fi
            done

  increment:
    executor: cli/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Increment Modified Orbs
          command: |
            namespace="moorara"
            version="dev:${CIRCLE_SHA1:0:7}"

            for orbpath in orbs/*/; do
              if [[ -d $orbpath ]]; then
                orbname=$(basename $orbpath)
                segment="patch"

                echo -e "\n\033[1;36m Publishing orb ${orbname} ... \033[0m"
                circleci orb publish increment "${orbpath}/orb.yml" "${namespace}/${orbname}" "$segment" --token "$CIRCLECI_API_TOKEN"
              fi
            done

workflows:
  publish-orbs:
    jobs:
      - lint
      - pack:
          context: dev
          requires:
            - lint
      - publish-dev:
          context: dev
          requires:
            - pack
      - increment:
          context: dev
          requires:
            - publish-dev
          filters:
            branches:
              only: master
